### PR TITLE
functional test

### LINKED ISSUE #23: find a way to functionally test the bundle
I noticed we introduced some bugs that didn't break the tests.

For instance if an incorrect class is used in `services.xml` you will only notice it when you include this bundle in your app and boot it.

There must be a way to properly test this.

### PR DESCRIPTION
**Pull request by othillo**
fixes #23

depends
- [x] #24 
- [x] #25

### CODE REVIEW

File: test/Functional/AppKernel.php [hunk 1]
```diff
@@ -0,0 +1,39 @@
+<?php
+
+/*
+ * This file is part of the broadway/broadway package.
```
Comment (asm89) [inline test/Functional/AppKernel.php:4]: nit: broadway/broadway-bundle?

**Review by asm89 — APPROVED** [review]

**Comment by asm89** [comment]
🎉
